name: Ruby Test Suite
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.2.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
    - name: Set up PostgreSQL
      uses: aiven/setup-postgres@v1
      with:
        postgresql_version: '13'
        postgresql_database: 'test_database'
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run Rubocop
      run: |
        bundle exec rubocop
    - name: Run RSpec
      env:
        RAILS_ENV: test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
      run: |
        bundle exec rspec