name: Ruby Test Suite
on: push
env:
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.2.1
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Install PostgreSQL client
      run: sudo apt-get install postgresql-client
    - name: Create test database
      run: |
        psql -c 'create database test_database;' -U postgres -h localhost -p 5432    
    - name: Run Rubocop
      run: |
        bundle exec rubocop
    - name: Run RSpec
      run: |
        bundle exec rspec
